### ISSUE TITLE
Possibility to define readonly fields in the detail views

### ISSUE THREAD

**Issue by chescales** [sanoma/django-arctic#76] opened 2016-10-03 14:29 UTC
It would be nice to be able to define read only fields in a list of field names, as this is a feature used in many models on a CMS.

For instance I have made a workaround on this by defining a base ModelForm, and using it as the view's form. The code looks like this:

```
class ReadOnlyModelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
            if kwargs.get('instance') and hasattr(self.Meta, 'readonly_fields'):
                initial = kwargs.get('initial', {})
                for readonly_field in self.Meta.readonly_fields:
                    if readonly_field in self.base_fields:
                        # Define model disabled field
                        self.base_fields[readonly_field].disabled = True
                    elif readonly_field not in self.declared_fields:
                        # If not in base fields, it should be previously defined, otherwise raise exc
                        raise RuntimeError(
                            "The form does not have any field '{}' defined. Please define it.".format(
                                readonly_field
                            )
                        )

                    # Define initial value
                    initial[readonly_field] = getattr(kwargs['instance'], readonly_field, None)

            super(ReadOnlyModelForm, self).__init__(*args, **kwargs)
```

With this you can define a Model form like: 

```
class SbUserForm(ReadOnlyModelForm):

    class Meta:
        model = SbUser
        fields = (
            'user',
            'user_type',
            'user_slug',
            'initials',
            'maiden_name',
            'gender',
            'dob',
            'birth_city',
            'current_city',
            'postal_code',
            'country',
            'phone',
            'mobile',
            'known_users',
        )
        readonly_fields = (
            'user_slug',
        )
```

Which is kind of convenient already, but forces us to define a ModelForm for every Model even if it's only to define a single read only field. If this could be done automatically at the view level it would be a great developer experience improvement. It would also prevent every Arctic user having to redefine the ReadOnlyModelForm again ;)

Please say if there is any simpler other approach that I may have missed.

Thanks!

**Comment by mmarcos** [comment] 2016-10-27 10:31
@aquatix is this still being worked on?

**Comment by mmarcos** [comment] 2016-11-06 12:00
duplicate of #72

**Closed by mmarcos** 2016-11-06 12:00 UTC
Labels: duplicate
